### ISSUE TITLE
安装此mod会导致林业和Binnie模组的所有本地化几乎全部丢失。

### ISSUE THREAD

**Issue by magcicada** [friendlyhj/NoLocalizationConflict#2]
如图所示：
![20220511163444](https://user-images.githubusercontent.com/45464670/167806104-e6ce3ee9-f800-4e14-b90c-061a30aa993c.png)

未检查log，且只使用所有基础mod测试可以复制该问题。

**Comment by magcicada** [comment]
解决设想是可不可以设个黑名单过滤一些会出问题的mod来避免该问题。

**Comment by friendlyhj** [comment]
你把游戏语言调成中文就好了 (x
相关修复正在搞
